version: '3.8'
services:
  user-service-db:
    image: postgres:15
    container_name: user-service-db
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - "5433:5432"
    volumes:
      - user-service-data:/var/lib/postgresql/data
    networks:
      - user-service-network
    restart: unless-stopped

networks:
  user-service-network:
    driver: bridge

volumes:
  user-service-data:
